[package]
name = "rabbit_mqin"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "send"
path = "src/send.rs"

[[bin]]
name = "receive"
path = "src/receive.rs"

[dependencies]
futures-lite = "2.6.1"
lapin = "3.7.2"
tokio = { version = "1.48.0", features = ["full"] }
